<a href="https://colab.research.google.com/github/KOdunga/AIMLCourse/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # Import numpy and abbreviate is as np. From now on we will call it using np

Numpy Arrays

- Like a list but can only accomodate the same data type for every entry
- A list can be converted to a numpy array

In [3]:
array_str = ['Merc', 'BMW','Toyota','Range','Tesla']
arr_num = [5,6,2,7,8]

In [4]:
#converting a list to an array. Creating an array from a list
np_arr_str = np.array(array_str)
np_arr_num = np.array(arr_num)

In [5]:
print(np_arr_str)
print(np_arr_num)

['Merc' 'BMW' 'Toyota' 'Range' 'Tesla']
[5 6 2 7 8]


In [6]:
type(np_arr_num)

numpy.ndarray

In [7]:
type(arr_num)

list

Numpy Matrix

- A 2 Dimensional data structure where elements are arranged as rows and columns
- Can be created using list of lists

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(type(matrix))

<class 'numpy.ndarray'>


In [10]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Numpy Functions
- Different ways to create numpy arrays using inbuilt functions

Arange
- Returns an array of numbers from the given start point to a given end point(exclude) and a given step point
- Default start value is 0
- Default step value is 1
- No default stop value

In [11]:

arr = np.arange(start = 0, stop = 10, step = 2) #define start =0, stop = 10, effectively, the value before 10
print(arr)

[0 2 4 6 8]


In [12]:
arr = np.arange(0,10) #stat is 0, stop is 10-1, default interval of 1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(3,10,2) # start is 3, stop is 10-1, imntervals of 2
print(arr)

[3 5 7 9]


In [14]:
arr = np.arange(9) #default start is 0, default step size is 1. end has to be defined
print(arr)

[0 1 2 3 4 5 6 7 8]


Linspace
- Returns a range of equally spaced values between two given numbers
- Default values returned is 50

In [15]:
lin_array = np.linspace(0,5)
print(lin_array)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [16]:
lin_array

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [17]:
lin_array = np.linspace(0,15,16) #Start at 0, stop at 15 (inclusive), return 16 values
print(lin_array)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


np.zeros()
- Used to create a matrix with only zeroes. Usefull when initiating a matrix
- You give the rows and columns.
- One can also specify the data type but by default it is float

In [18]:
arr_zero = np.zeros([3,5]) # rows =3 , columns = 5. rows first
arr_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones()

In [19]:
arr_one= np.ones([4,6])
arr_one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Identity Matrix
- This is a square matrix, where number of rows is equal to number of columns and all values are zero except the number where row = column == 1 (elements of the principal diagonal are equal to 1)
- This is used in linear algebraic functions
- The np.eye() funtion is used and only the number of rows / columns is entered as a parameter

In [20]:
arr_i = np.eye(5)
print(arr_i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Manipulating Arrays using Reshape Function
- Allows us to reshape a list into the number of rows and columns that we want
- These are specified in a tuple parameter submitted to the reshae() function
- The output is a return value that has to be assigned to new variable as the initial one remians unchanged

In [21]:
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr4_reshaped = arr4.reshape(2,5) #Reshape the input from arr4 into a 2 rows by 5 columns output and assign it to a variable called arr4_reshaped
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Mathematical functions of numpy

In [24]:
np.sin(4) # calculates the sin of 4 and returns in radians

-0.7568024953079282

In [25]:
np.tan(4) # tangent of 4

1.1578212823495775

In [26]:
np.sin(arr4) # calculates the sin of every single entry in arr4.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [27]:
np.tan(arr4_reshaped)

array([[ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566]])

In [28]:
#Natural exponential
np.exp(2)

7.38905609893065

In [29]:
arr5 =np.exp(arr4)
arr5

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [30]:
np.exp([4,5,6]) #input a list

array([ 54.59815003, 148.4131591 , 403.42879349])

In [31]:
#Logarithms. By default, numpy uses log base e
np.log(2)

0.6931471805599453

In [32]:
np.log(arr5)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
#log with base 10
np.log10(1)

0.0

In [34]:
np.log10(0)

<ipython-input-34-fb8478a94c6a>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(0)


-inf

In [35]:
np.log2(8) #log base 2

3.0

Arithmetic Operations on Numpy Arrays

In [36]:
l1 = [1,2,3,4]
l2 = [3,4,5,6]
l1+l2 #only concatenates the list and does not do the internal additions

[1, 2, 3, 4, 3, 4, 5, 6]

In [37]:
l1_array = np.array(l1)
l2_array = np.array(l2)
l1_array+l2_array #After converting to arrays, we can now do mathematics on the values

array([ 4,  6,  8, 10])

In [38]:
l2_array- l1_array

array([2, 2, 2, 2])

In [39]:
l1_array*l2_array #Returns an element wise multiplication

array([ 3,  8, 15, 24])

In [40]:
l2_array/l1_array

array([3.        , 2.        , 1.66666667, 1.5       ])

In [41]:
1/l1_array #Inverse

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [42]:
l2_array**l1_array # Double star is used for powers in python. DO not use the carat ^ like in other languages

array([   3,   16,  125, 1296])

Operation on Matrices

In [43]:
matrix1 = np.arange(1,10).reshape(3,3)
matrix2 = np.eye(3)
print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
matrix1+matrix2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [45]:
print(matrix1/matrix2)

[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


<ipython-input-45-c079c72c35c0>:1: RuntimeWarning: divide by zero encountered in divide
  print(matrix1/matrix2)


Perfoming a true linear algebra matrix dot product

In [46]:
matrixa = np.arange(1,5).reshape(2,2)
matrixb= np.arange(3,7).reshape(2,2)
print(matrixa)
print(matrixb)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [49]:
matrixa*matrixb # normal element by element matrix mulitplication

array([[ 3,  8],
       [15, 24]])

In [51]:
matrixa@matrixb #Linear algebraic dot product matrix multiplication

array([[13, 16],
       [29, 36]])

Transposing a matrix using transpose() or.T

In [53]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
matrix1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
np.transpose(matrix1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Other Functions

In [56]:
print("Minimum",np.min(matrix1)) #get the smallest value

Minimum 1


In [58]:
print("Max",np.max(matrix1)) #get the largest value

Max 9


Function to generate random numbers
- matrix.random.rand(n) where n is the number of values to generate
- Usually generates values between 0 and 1, randomly.

In [61]:
rand_num = np.random.rand(5)
print(rand_num)

[0.56346079 0.45243319 0.05003666 0.78720005 0.82061571]


In [62]:
rand_num

array([0.56346079, 0.45243319, 0.05003666, 0.78720005, 0.82061571])

In [63]:
rand_num_matrix = np.random.rand(5,5) #generate a 5 by 5 matrix with random numbers
print(rand_num_matrix)

[[0.2681048  0.95072161 0.8282465  0.58616999 0.35725964]
 [0.20004129 0.23484462 0.61342091 0.64902964 0.4887067 ]
 [0.43181858 0.55883116 0.72767741 0.10880188 0.33483344]
 [0.18258392 0.93633465 0.56604082 0.65229219 0.79020795]
 [0.82711226 0.20276598 0.34734815 0.91291969 0.27978687]]


The rand functions generates probability random numbers (between 0 and 1, or 0% to 100%).
If you want to generate numbers randomly from the standard normal distribution (Gaussian distribution) you use the randn() function instead.

In [66]:
normal_rand_numbers = np.random.randn(5)
print(normal_rand_numbers)

[ 0.15233874  1.1547239  -0.20685422 -1.27060819 -1.67179813]


In [77]:
normal_rand_matrix = np.random.randn(5,5)
print(normal_rand_matrix)

[[ 0.36016312 -0.96602203 -1.44699746 -0.72511209  2.08682802]
 [ 2.41063866 -0.77168586 -0.76623311 -1.49072407 -0.08403522]
 [-0.49990276 -0.92424274  0.50192952 -1.25697867 -0.36609825]
 [ 1.4118525   1.18369032  0.16004799 -0.80168233 -0.1527975 ]
 [-0.55396235  1.20664578 -0.97291762 -0.85317359 -0.27189043]]


In [78]:
np.mean(rand_num_matrix)

0.5214360260661203

In [79]:
np.std(rand_num_matrix)

0.25747202491398097

Generate random integer numbers
- Use randint fucntion inside of random function()
- Specify the start (inclusive) and the stop (exclusive) and the size, i.e number of elements to generate

In [82]:
random_integers = np.random.randint(1,5,10)
print(random_integers)

[3 2 4 2 2 1 1 4 3 3]


In [87]:
#Making a random integer matrix
random_integers = np.random.randint(1,10,[5,5]) # Make us of a list in the size parameter
print(random_integers)

[[4 9 8 4 5]
 [5 9 8 6 7]
 [2 3 4 8 1]
 [3 7 1 2 7]
 [3 7 1 6 7]]


Accessing Numpy Arrays

In [99]:
rand_arr = np.random.randn(10)
print(rand_arr)

[-1.00073088 -1.974555   -0.1950381  -0.23868358 -0.87920163  1.1808772
  0.1748269   0.47034843  2.47566485  0.54235607]


In [100]:
print(rand_arr[6]) #the sixth element, same as in lists

0.1748269029015549


In [101]:
print(rand_arr[4:9])

[-0.87920163  1.1808772   0.1748269   0.47034843  2.47566485]


In [102]:
print(rand_arr[4:-3])

[-0.87920163  1.1808772   0.1748269 ]


In [103]:
print(rand_arr[np.arange(3,10,3)])

[-0.23868358  0.1748269   0.54235607]


Accessing items using logical indexing

In [104]:
print(rand_arr)

[-1.00073088 -1.974555   -0.1950381  -0.23868358 -0.87920163  1.1808772
  0.1748269   0.47034843  2.47566485  0.54235607]


In [105]:
print('Values greater than 0: ', rand_arr>0)

Values greater than 0:  [False False False False False  True  True  True  True  True]


In [108]:
print('Values greater than 0: ', rand_arr[rand_arr>0])

Values greater than 0:  [1.1808772  0.1748269  0.47034843 2.47566485 0.54235607]


In [109]:
print('Values greater than 0: ', rand_arr[rand_arr<0])

Values greater than 0:  [-1.00073088 -1.974555   -0.1950381  -0.23868358 -0.87920163]


Accesing Values in a Matrix

In [112]:
rand_matrix = np.random.randn(5,5)
rand_matrix

array([[-1.17519884, -0.06632196,  0.55368892, -3.19116873, -1.86611526],
       [-1.10279344,  1.1646984 ,  0.14928526, -1.45319514, -0.98552686],
       [-0.2386818 , -1.09290935, -0.30560246, -0.44992808,  1.97548348],
       [-0.7614005 ,  0.09423889,  0.28760082,  0.1354341 ,  0.46080232],
       [ 1.7139424 ,  0.16845018,  0.20657327, -0.72794513,  2.3701577 ]])

In [114]:
rand_matrix[1] #return only the first row

array([-1.10279344,  1.1646984 ,  0.14928526, -1.45319514, -0.98552686])

In [117]:
print(rand_matrix[1][2]) #To return a particulr value of a matrix
#or it can lso be implemented using a comma separated row, column value

print(rand_matrix[1,2])

0.14928526404829215
0.14928526404829215


In [119]:
#accesing rows 0 and 1 and columns 1 and 2
print(rand_matrix[0:2,1:3])

[[-0.06632196  0.55368892]
 [ 1.1646984   0.14928526]]


In [124]:
print('Values that are greater than 0:\n\n', rand_matrix[rand_matrix>0]) #This command will abandon the matrix structure and just return a list

Values that are greater than 0:

 [0.55368892 1.1646984  0.14928526 1.97548348 0.09423889 0.28760082
 0.1354341  0.46080232 1.7139424  0.16845018 0.20657327 2.3701577 ]


Modifying Values of an Array

In [126]:
print(rand_matrix)

[[-1.17519884 -0.06632196  0.55368892 -3.19116873 -1.86611526]
 [-1.10279344  1.1646984   0.14928526 -1.45319514 -0.98552686]
 [-0.2386818  -1.09290935 -0.30560246 -0.44992808  1.97548348]
 [-0.7614005   0.09423889  0.28760082  0.1354341   0.46080232]
 [ 1.7139424   0.16845018  0.20657327 -0.72794513  2.3701577 ]]


In [127]:
rand_matrix[3:5] = 7
print(rand_matrix)

[[-1.17519884 -0.06632196  0.55368892 -3.19116873 -1.86611526]
 [-1.10279344  1.1646984   0.14928526 -1.45319514 -0.98552686]
 [-0.2386818  -1.09290935 -0.30560246 -0.44992808  1.97548348]
 [ 7.          7.          7.          7.          7.        ]
 [ 7.          7.          7.          7.          7.        ]]


In [132]:
rand_matrix[rand_matrix>6] = 8 #Modification using logiaca references
rand_matrix

array([[-1.17519884, -0.06632196,  0.55368892, -3.19116873, -1.86611526],
       [-1.10279344,  1.1646984 ,  0.14928526, -1.45319514, -0.98552686],
       [-0.2386818 , -1.09290935, -0.30560246, -0.44992808,  1.97548348],
       [ 8.        ,  8.        ,  8.        ,  8.        ,  8.        ],
       [ 8.        ,  8.        ,  8.        ,  8.        ,  8.        ]])

In [138]:
new_matrix = np.random.randint(5,100,[5,5])
print(new_matrix)

[[47 77 82 21 24]
 [42 39 65 55 84]
 [77 59 75 61 55]
 [41 52 15 12 37]
 [14 98 16 21 32]]


In [139]:
new_matrix[1:3,3:5] = 0
print(new_matrix)

[[47 77 82 21 24]
 [42 39 65  0  0]
 [77 59 75  0  0]
 [41 52 15 12 37]
 [14 98 16 21 32]]


In [142]:
sub_mat = new_matrix[0:2,1:4]
print(sub_mat)

[[77 82 21]
 [39 65  0]]


In [143]:
sub_mat[:]=3
print(sub_mat)

[[3 3 3]
 [3 3 3]]


In [145]:
print(new_matrix) # original matrix is also changed

[[47  3  3  3 24]
 [42  3  3  3  0]
 [77 59 75  0  0]
 [41 52 15 12 37]
 [14 98 16 21 32]]


In [152]:
#To avoid this, you can make a copy of the original matrix using .copy() function
rand_mat = np.random.randn(5,5)
print("Original Rand Matrix\n",rand_mat)
sub_mat = rand_mat[0:2,1:3].copy() #copy command
print("Original submat\n",sub_mat)
sub_mat[:] = 4
print("Modified Submat\n",sub_mat)
print("Unmodified original matrix\n",rand_mat)


Original Rand Matrix
 [[ 0.28425802  0.72517688 -0.85764492  0.06973897  0.95105695]
 [-1.54449666  0.44660157 -0.50852673  1.73898327  0.72686543]
 [ 0.37870147  1.07663698  0.63586275  0.60110056  0.18863228]
 [ 2.20339853 -0.99219165 -0.43672567  1.79433636  0.44002743]
 [-0.21495316 -1.18472925 -0.82280758  2.19074423  0.3363827 ]]
Original submat
 [[ 0.72517688 -0.85764492]
 [ 0.44660157 -0.50852673]]
Modified Submat
 [[4. 4.]
 [4. 4.]]
Unmodified original matrix
 [[ 0.28425802  0.72517688 -0.85764492  0.06973897  0.95105695]
 [-1.54449666  0.44660157 -0.50852673  1.73898327  0.72686543]
 [ 0.37870147  1.07663698  0.63586275  0.60110056  0.18863228]
 [ 2.20339853 -0.99219165 -0.43672567  1.79433636  0.44002743]
 [-0.21495316 -1.18472925 -0.82280758  2.19074423  0.3363827 ]]


Saving FIles

In [157]:
#Use np.save
#you have to mount your drive to google drive first
np.save('/content/sample_data', random_integers)
#savez() will save multiple files at one go

Loading Files

In [158]:
loaded_arr = np.load('/content/sample_data.npy')
print(loaded_arr)

[[4 9 8 4 5]
 [5 9 8 6 7]
 [2 3 4 8 1]
 [3 7 1 2 7]
 [3 7 1 6 7]]
